server:
  port: 8900
#  servlet:
#    context-path: /note
spring:
  application:
    name: enegry

  thymeleaf:
    cache: false
  datasource:
    master:
          url: jdbc:mysql://11.11.11.100:3306/energydb?useSSL=false
          username: opviewuser
          password: opview4/25
    # \u4F7F\u7528druid\u6570\u636E\u6E90
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
    cluster:
      - key: slaver1
        password: opview4/25
        url: jdbc:mysql://11.11.11.100:3306/cinder?glanceuseSSL=false
        idle-timeout: 20000
        driver-class-name: com.mysql.jdbc.Driver
        username: opviewuser
        type: com.zaxxer.hikari.HikariDataSource
      - key: test
        password: pxieloveQAQ()
        url: jdbc:mysql://cdb-fmyiu6q7.gz.tencentcdb.com:10045/blog?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root

        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
       include: "*"  # * 在yaml 文件属于关键字，所以需要加引号